title: Erik Grip
logo: "/images/erik_grip.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  These are a few ML and data analytics projects I've done because I couldn't help myself.
  <br><br>
  <a href="https://www.linkedin.com/in/erikgrip/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: G-VZW1PEMG9Y # your Google Analytics tracking ID here
